version: '3.2'

services:
  postgres:
    image: 'postgis/postgis:12-3.0-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: ./finder_data
        target: /var/lib/postgresql/data
